version: '3.8'
services:
  web:
    build: .
    container_name: web_app
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: webapp_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

